### ISSUE TITLE
Needs to test if [System.Console] is available

### ISSUE THREAD

**Issue by KevinLeeBuchan** [CollinChaffin/Get-MSDNBlogEbooks.ps1#1] opened 2015-07-21 11:52 UTC
Errors when running in PowerGui.
# Use csharp method to write to console - better same-line progress and less obtrusive than Write-Progress

[System.Console]::CursorLeft = 0
[System.Console]::BackGroundColor = 'Black'
[System.Console]::ForeGroundColor = 'Yellow'                

[Edit]
I did a quick google and saw this as a solution to the errors, but looks wonky in PowerGui.
Note that the second string must be at least as long as the first, or padright with spaces, but you already know that, from your own code.
write-host "Test" -ForegroundColor Yellow -BackgroundColor Black -NoNewline
start-sleep -s 1
write-host "`rTest2" -ForegroundColor yellow -BackgroundColor Black

**Comment by CollinChaffin** [comment] 2016-04-11 21:06
Closing as you did not post errors and I cannot reproduce.  If you want to reopen an issue and post the exact errors you are receiving, I will look into it.

**Closed as completed by CollinChaffin** 2016-04-11 21:06 UTC
